plugins: [jekyll-paginate]

permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: "page/:num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,gitment.css,post.css]
      scripts : [gitment.js, post.js]



title: "zhwly"
email: A15216114872@gmail.com
description: ""
github:
  username: zhwly
swiftype:
  searchId: iXZyPokVfxFaBTvi64Y6
gitment:
    repo: zhwly.github.io
    client_id: bf36d4c78dcdfe31cfd0
    client_secret: 98e0a2a454adbee7714fd5e9edc8e2fca47fe404

url: "https://github.com/zhwly/zhwly.github.io"
imgrepo: "https://github.com/zhwly/zhwly.github.io/static/img"


#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

