plugins: [jekyll-paginate]

permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: "page/:num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,gitment.css,post.css]
      scripts : [gitment.js, post.js]



title: "zhwly"
email: A15216114872@gmail.com
description: "这就是一个现代森林里的边陲小木屋，也许能有你需要的。"
github:
  username: zhwly
swiftype:
  searchId: W5LEmaNJzSQEsrhZkR2J
gitment:
    repo: 评论
    client_id: bf36d4c78dcdfe31cfd0
    client_secret: 98e0a2a454adbee7714fd5e9edc8e2fca47fe404

url: "https://zhwly.github.io"
imgrepo: "https://zhwly.github.io/static/img"


#url: "https://github.com/zhwlyzhwly.github.io/"
#imgrepo: "https://github.com/zhwly/zhwly.github.io/static/img"

